spring.application.name=mspagamento
server.port=8080

#jdbc:postgresql://localhost:5432/grg_lab_d
spring.datasource.url=${PSQL_HOST}
spring.datasource.username=postgres
spring.datasource.password=${PSQL_PASSWD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

aws.sqs.queue.url=${SQS_URL}

spring.jackson.default-property-inclusion=non_null

pagseguro.url.orders=https://sandbox.api.pagseguro.com/orders
pagseguro.token=${PAGSEGURO_TOKEN}