spring.application.name=mspagamento
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/grg_lab_d
spring.datasource.username=postgres
spring.datasource.password=2AkByM4NfHFkeJz

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

aws.sqs.queue.url=https://sqs.us-east-1.amazonaws.com/260761541415/ms-pagseg-psql-queue



spring.jackson.default-property-inclusion=non_null

pagseguro.url.orders=https://sandbox.api.pagseguro.com/orders
pagseguro.token=0cf952df-8d71-4857-aa44-14cdd833a99d06d806774a4a9a98e49efa052757fb8dc456-5d0e-451a-8fb1-364c12487e2a